### ISSUE TITLE
Switching to Chinese/Korean IMEs produce Latin/QWERTY output until switching windows

### ISSUE THREAD

**Issue by casouri** [mitsuse/swim#1]
Same issue as in here: vovkasm/input-source-switcher#5
Could you have a look into it?

**Comment by mitsuse** [comment]
@casouri Thanks for reporting. Please wait for a while.

**Comment by casouri** [comment]
Any news yet?

**Comment by mitsuse** [comment]
@casouri  The issue is not resolved yet. But I observed a issue on switching the input method normally similar to one reported here. We may be able to investigate more and add some workarounds to resolve the issue but I’m unwilling to do it because I suspect the problem is caused by OS.

However, if you have any ideas to resolve this issue, don’t hesitate to submit pull-requests!

**Comment by casouri** [comment]
I like your cat. 😊


I can look into the code sometime when I have finished what I'm doing now.

Do you mind keep this issue open until there is a fix?

**Comment by mitsuse** [comment]
@casouri 

OK, I will keep this issue open.

> I Like your cat.

Thanks!! :cat:

**Comment by mitsuse** [comment]
This problem doesn't seems to be reproduced on macOS 10.14.

**Comment by casouri** [comment]
Haven't been using it lately but great to hear :smile:
